=== SuryaTeja-koka/EP-PROJECTS/prac2/WebContent/postlab.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="student-info">
<xs:complexType>
<xs:sequence>
<xs:element name="student" minOccurs="5" maxOccurs="10">
<xs:complexType>
<xs:sequence>
<xs:element name="id" type="xs:int" />
<xs:element name="name" type="xs:string" />
<xs:element name="avg" type="xs:decimal" />
<xs:element name="dob" type="xs:date" />
<xs:element name="time" type="xs:time" />
<xs:element name="mobile">
<xs:simpleType>
<xs:restriction base="xs:decimal">
<xs:minInclusive value="1000000000"></xs:minInclusive>
<xs:maxInclusive value="9999999999"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="distinction" type="xs:string" />

</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== SuryaTeja-koka/EP-PROJECTS/prac2/WebContent/postlab.xml
<?xml version="1.0" encoding="UTF-8"?>
<student-info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="postlab.xsd">
<student>   			
   <id>3</id>
   <name>surya</name>    
   <avg>91</avg>
   <dob>2001-11-18</dob>  
   <time>08:25:53</time>       
   <mobile>8179887926</mobile>	   
   <distinction>YES</distinction>
 </student>
 <student>   			
   <id>31554</id>
   <name>surya</name>    
   <avg>86</avg>
   <dob>2001-09-03</dob>  
   <time>12:00:00</time>       
   <mobile>9949512482</mobile>  		   
   <distinction>YES</distinction>
 </student>
 <student>   			
   <id>31554</id>
   <name>surya</name>    
   <avg>86</avg>
   <dob>2001-09-03</dob>  
   <time>12:00:00</time>       
   <mobile>9949512482</mobile>  		   
   <distinction>YES</distinction>
 </student>

 <student>   			
   <id>31554</id>
   <name>surya</name>    
   <avg>86</avg>
   <dob>2001-09-03</dob>  
   <time>12:00:00</time>       
   <mobile>9949512482</mobile>  		   
   <distinction>YES</distinction>
 </student>
 
<student>   			
   <id>31554</id>
   <name>surya</name>    
   <avg>86</avg>
   <dob>2001-09-03</dob>  
   <time>12:00:00</time>       
   <mobile>9949512482</mobile>  		   
   <distinction>YES</distinction>
 </student>

</student-info>
